paths:
  raw_data: "data/raw/solidity_re_entrancy_dataset"
  processed_data: "data/processed/tokenized_dataset"
  models_dir: "models/t5-finetuned"

training:
  learning_rate: 2e-5
  batch_size: 8
  num_epochs: 3
  weight_decay: 0.01
